### ISSUE TITLE
Provide a Homebrew tap for macOS and Linux

### ISSUE THREAD

**Issue by davidperrenoud** [BrickBot/nqc#4]
I made my own [Homebrew tap](https://github.com/davidperrenoud/homebrew-nqc) using [jverne/nqc](https://github.com/jverne/nqc) so that you can install nqc on macOS by typing:
```
brew install davidperrenoud/nqc/nqc
```

This will download the compiled version (bottle) on macOS 12 Intel and compile it from source on other architecture such as ARM or macOS versions.

You could provide the same functionality with the following formula:
```
class Nqc < Formula
  desc "Programming language for LEGO MINDSTORMS RCX, CyberMaster and Scout"
  homepage "https://bricxcc.sourceforge.net/nqc/"
  url "https://github.com/BrickBot/nqc/archive/refs/tags/v3.1-r6.tar.gz"
  version "3.1r6"
  sha256 "24aaa060f438606965ce17986af2e3e91ea9ccba7ffb4687ee6f89f3cd4ee585"
  license "MPL-2.0"

  def install
    ENV.deparallelize
    system "make", "install", "PREFIX=#{prefix}", "MANDIR=#{man}/man1"
  end

  test do
    system "#{bin}/nqc", "-help"
  end
end
```

As your repository is compatible with Linux, you do **not** need to add `depends_on :macos`.

You can configure your repository to automatically upload macOS 12 Intel and Ubuntu 22.04 bottles with the following guide:
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

Other architectures are only available in [homebrew-core](https://github.com/Homebrew/homebrew-core) but they do not allow repositories with less than 75 stars.

**Comment by mesheets** [comment]
Hello @davidperrenoud , thank you for the feedback!  It appears the first thing that would be needed is a, say, "homebrew-nqc" repository created?  If you, and if you might be interested in helping to get the homebrew tap going, I could create the needed repository and add you as a maintainer.

**Comment by mesheets** [comment]
https://github.com/BrickBot/homebrew-nqc created.
